### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/docs#6]
Contractions are being counted as code quotes. Is there a way to detect common words vs code?

https://docs.dbatools.io/#Add-DbaPfDataCollectorCounter

**Comment by niphlod** [comment]
don't know what "contractions" are but if you mean differencing "code" vs "the explanation of what happens when that line of code runs" I don't think so. 
PS doesn't differentiate. We *could* do so that "the very first line is code, everything else is the explanation" but it's not a deterministic way to detect, it's just a "made up convention" we'd need to adhere to.

BTW: a better detection *could* be example lines starting with `PS C:\>` that seems consistent. Again, this is just convention.

**Comment by niphlod** [comment]
Uh, ok, lemme see but, as a general rule, if cbh is markdown and markdown
renders that way, cbh is the thing that needs fixing. Will take a look
however.

Il lun 17 set 2018, 07:23 Shawn Melton <notifications@github.com> ha
scritto:

**Comment by wsmelton** [comment]
Well the example on there for `Get-DbaBackupInformation` has the code formatted with line breaks on the piping symbol. In that particular case it needs to be all one line to show that ability. I don't see us being able to make every example just one line though simply due to the complexity on some of the commands. (Primary example of this is the `Invoke-DbaLogShipping` command:

https://github.com/sqlcollaborative/dbatools/blob/14a0632f5e2eaedb52303a168cf0a00cef7f34f3/functions/Invoke-DbaLogShipping.ps1#L346-L370

If we go with the method used in main PS examples and start each "new line of code" with the `PS C:\>`, could we then parse it differently for the index?

**Comment by niphlod** [comment]
Need to play more and see how the rendered output from get-help interprets
examples "code" Vs "explanation of what the code does"

Il lun 24 set 2018, 07:34 Shawn Melton <notifications@github.com> ha
scritto:

**Comment by niphlod** [comment]
@wsmelton struck gold. The parser shortcircuits around  `PS C:\>` ...
We can pass to the "better renderer" with the only culprit of *needing/adding* `PS C:\>` to whatever multiline example we have. Single lines one won't need it, but if they are there then no problem at all. 
If @potatoqualitee is also willing to go this route, I'll gladly add the new snippet.

**Comment by niphlod** [comment]
closed with the new "rendering engine"
